name: IPFS

on:
  push:
    branches: ['main']
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
      - run: echo "/home/linuxbrew/.linuxbrew/bin:/home/linuxbrew/.linuxbrew/sbin" >> $GITHUB_PATH
      - run: brew install ipfs
      - name: Install vss cli
        run: make setup
      - name: Build with vss
        run: make build
      - run: ipfs init
      - run: ipfs add -r dist
      - run: ipfs pin add QmT3YJXwYMVhAouUfE6ZeSKeX41RhUdiuJno3XrV9CJHsb
      - run: ipfs name publish QmT3YJXwYMVhAouUfE6ZeSKeX41RhUdiuJno3XrV9CJHsb